/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.views;

/**
 *
 * @author notebook
 */
public class AddExpense extends javax.swing.JPanel {

    /**
     * Creates new form Home
     */
    public AddExpense() {
        initComponents();
        InitStyles();
    }

    private void InitStyles() {
        Titulo.putClientProperty("FlatLaf.styleClass", "h3");
        Subtitulo1.putClientProperty("FlatLaf.styleClass", "h4");
        jButton1.putClientProperty( "JButton.buttonType", "roundRect" );
//        Subtitulo2.putClientProperty("FlatLaf.styleClass", "h4");
//        Tituloq.putClientProperty("FlatLaf.styleClass", "h3");
//        Item1.putClientProperty("FlatLaf.styleClass", "h4");
//        Item2.putClientProperty("FlatLaf.styleClass", "h4");
//        Item3.putClientProperty("FlatLaf.styleClass", "h4");
//        Item4.putClientProperty("FlatLaf.styleClass", "h4");
//        Item5.putClientProperty("FlatLaf.styleClass", "h4");
//        Item6.putClientProperty("FlatLaf.styleClass", "h4");        
        Titulo.putClientProperty("FlatLaf.style", "font: bold $h1.regular.font");

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bg = new javax.swing.JPanel();
        Titulo = new javax.swing.JLabel();
        Subtitulo1 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox<>();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(558, 451));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        bg.setBackground(new java.awt.Color(255, 255, 255));
        bg.setPreferredSize(new java.awt.Dimension(558, 451));
        bg.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Titulo.setText("Agregar un nuevo gasto");
        bg.add(Titulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(147, 0, 363, -1));

        Subtitulo1.setText("Aquí puedes ingresar un nuevo gasto a tu lista para poder llevar el control del pago.");
        bg.add(Subtitulo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 34, 483, -1));

        jLabel11.setText("Empieza a organizar tus gastos ahora mismo. Si necesitas ayuda, estamos aquí para ti.  ");
        bg.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 410, 483, -1));

        jLabel13.setText("¡Gracias por elegirnos!  ");
        bg.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 517, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/money.png"))); // NOI18N
        bg.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 120, 250, 200));

        jButton1.setBackground(new java.awt.Color(129, 172, 0));
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Agregar Gasto");
        jButton1.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(64, 124, 0)));
        jButton1.setBorderPainted(false);
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        bg.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 360, 201, 41));

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        bg.add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 250, -1, -1));

        jTextField1.setText("Ingrese el nombre  del gasto...");
        jTextField1.setSelectionColor(new java.awt.Color(153, 204, 0));
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        bg.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 110, 186, -1));

        jTextField2.setSelectionColor(new java.awt.Color(153, 204, 0));
        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });
        bg.add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 300, 120, -1));

        jLabel1.setText("Nombre o descripción del gasto.");
        bg.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 80, 186, -1));
        bg.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 140, 186, 10));
        bg.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 210, 186, 10));

        jLabel3.setText("Cantidad de cuotas");
        bg.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 220, 186, -1));

        jLabel4.setText("Fecha de vencimiento");
        bg.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 280, 186, -1));

        jLabel5.setText("Monto total del gasto");
        bg.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 160, 186, -1));

        jTextField3.setText("Ingrese el monto total del gasto...");
        jTextField3.setSelectionColor(new java.awt.Color(153, 204, 0));
        jTextField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField3ActionPerformed(evt);
            }
        });
        bg.add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 180, -1, -1));

        add(bg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 564, 430));
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField3ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Subtitulo1;
    private javax.swing.JLabel Titulo;
    private javax.swing.JPanel bg;
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    // End of variables declaration//GEN-END:variables
}
