/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.views;

/**
 *
 * @author notebook
 */
public class Home extends javax.swing.JPanel {

    /**
     * Creates new form Home
     */
    public Home() {
        initComponents();
        InitStyles();
    }

    private void InitStyles() {
        Titulo.putClientProperty("FlatLaf.styleClass", "h3");
        Subtitulo1.putClientProperty("FlatLaf.styleClass", "h4");
        Subtitulo2.putClientProperty("FlatLaf.styleClass", "h4");
        Tituloq.putClientProperty("FlatLaf.styleClass", "h3");
        Item1.putClientProperty("FlatLaf.styleClass", "h4");
        Item2.putClientProperty("FlatLaf.styleClass", "h4");
        Item3.putClientProperty("FlatLaf.styleClass", "h4");
        Item4.putClientProperty("FlatLaf.styleClass", "h4");
        Item5.putClientProperty("FlatLaf.styleClass", "h4");
        Item6.putClientProperty("FlatLaf.styleClass", "h4");        
        Titulo.putClientProperty("FlatLaf.style", "font: bold $h1.regular.font");

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bg = new javax.swing.JPanel();
        Titulo = new javax.swing.JLabel();
        Img1 = new javax.swing.JLabel();
        Subtitulo1 = new javax.swing.JLabel();
        Subtitulo2 = new javax.swing.JLabel();
        Tituloq = new javax.swing.JLabel();
        Item6 = new javax.swing.JLabel();
        Item1 = new javax.swing.JLabel();
        Item3 = new javax.swing.JLabel();
        Item4 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        Item2 = new javax.swing.JLabel();
        Item5 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(558, 451));

        bg.setBackground(new java.awt.Color(255, 255, 255));
        bg.setPreferredSize(new java.awt.Dimension(558, 451));

        Titulo.setText("Hola {User.name}");

        Img1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hometest.png"))); // NOI18N

        Subtitulo1.setText("Nos complace darte la bienvenida a tu nuevo compañero en la gestión eficaz de tus gastos");

        Subtitulo2.setText("mensuales con nuestra aplicación, gestionar tu presupuesto nunca ha sido tan sencillo.");

        Tituloq.setText("¿Qué puedes hacer con gastAPP?");

        Item6.setText("● Tener privacidad en tus cuentas");

        Item1.setText("● Crear múltiples usuarios");

        Item3.setText("● Realizar una lista completa");

        Item4.setText("● Ver todos los vencimientos");

        jLabel11.setText("Empieza a organizar tus gastos ahora mismo. Si necesitas ayuda, estamos aquí para ti.  ");

        Item2.setText("● Agregar y eliminar gastos");

        Item5.setText("● Controlar fechas de pago");

        jLabel13.setText("¡Gracias por elegirnos!  ");

        javax.swing.GroupLayout bgLayout = new javax.swing.GroupLayout(bg);
        bg.setLayout(bgLayout);
        bgLayout.setHorizontalGroup(
            bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bgLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(bgLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(Subtitulo1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(bgLayout.createSequentialGroup()
                        .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(bgLayout.createSequentialGroup()
                                .addGap(170, 170, 170)
                                .addComponent(Img1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                            .addGroup(bgLayout.createSequentialGroup()
                                .addComponent(Tituloq, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(348, 348, 348))
                            .addGroup(bgLayout.createSequentialGroup()
                                .addComponent(Item3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(360, 360, 360))
                            .addGroup(bgLayout.createSequentialGroup()
                                .addComponent(Item2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(370, 370, 370))
                            .addGroup(bgLayout.createSequentialGroup()
                                .addComponent(Item4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(360, 360, 360))
                            .addGroup(bgLayout.createSequentialGroup()
                                .addComponent(Item6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(330, 330, 330))
                            .addGroup(bgLayout.createSequentialGroup()
                                .addComponent(Item1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(370, 370, 370))
                            .addGroup(bgLayout.createSequentialGroup()
                                .addComponent(Item5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(360, 360, 360))
                            .addGroup(bgLayout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(Subtitulo2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(66, 66, 66)))
                        .addGap(90, 90, 90))))
            .addGroup(bgLayout.createSequentialGroup()
                .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(bgLayout.createSequentialGroup()
                        .addGap(210, 210, 210)
                        .addComponent(Titulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(222, 222, 222))
                    .addGroup(bgLayout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(bgLayout.createSequentialGroup()
                        .addGap(220, 220, 220)
                        .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(178, 178, 178)))
                .addGap(116, 116, 116))
        );
        bgLayout.setVerticalGroup(
            bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bgLayout.createSequentialGroup()
                .addComponent(Titulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(4, 4, 4)
                .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Img1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(bgLayout.createSequentialGroup()
                        .addGap(280, 280, 280)
                        .addComponent(Item6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(61, 61, 61))
                    .addGroup(bgLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(Subtitulo1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(321, 321, 321))
                    .addGroup(bgLayout.createSequentialGroup()
                        .addGap(130, 130, 130)
                        .addComponent(Item1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(211, 211, 211))
                    .addGroup(bgLayout.createSequentialGroup()
                        .addGap(190, 190, 190)
                        .addComponent(Item3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(151, 151, 151))
                    .addGroup(bgLayout.createSequentialGroup()
                        .addGap(160, 160, 160)
                        .addComponent(Item2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(181, 181, 181))
                    .addGroup(bgLayout.createSequentialGroup()
                        .addGap(250, 250, 250)
                        .addComponent(Item5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(91, 91, 91))
                    .addGroup(bgLayout.createSequentialGroup()
                        .addGap(220, 220, 220)
                        .addComponent(Item4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(121, 121, 121))
                    .addGroup(bgLayout.createSequentialGroup()
                        .addGap(90, 90, 90)
                        .addComponent(Tituloq, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(251, 251, 251))
                    .addGroup(bgLayout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(Subtitulo2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(301, 301, 301)))
                .addGap(3, 3, 3)
                .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(4, 4, 4)
                .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(38, 38, 38))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(bg, javax.swing.GroupLayout.PREFERRED_SIZE, 553, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.DEFAULT_SIZE, 454, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Img1;
    private javax.swing.JLabel Item1;
    private javax.swing.JLabel Item2;
    private javax.swing.JLabel Item3;
    private javax.swing.JLabel Item4;
    private javax.swing.JLabel Item5;
    private javax.swing.JLabel Item6;
    private javax.swing.JLabel Subtitulo1;
    private javax.swing.JLabel Subtitulo2;
    private javax.swing.JLabel Titulo;
    private javax.swing.JLabel Tituloq;
    private javax.swing.JPanel bg;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    // End of variables declaration//GEN-END:variables
}
